%%
function header = getVideoConfigHeader()
    header = {'Enable', 'Name', 'Dmy1', 'Start', 'End', 'All', 'fps', 'TH', 'mmPixel', 'ROI', 'rej_dist', 'isInvert', ...
        'G_Strength','G_Radius', 'AreaPixel', 'Step', 'BlobSeparate', ...
        'FilterType', 'MaxSeparate', 'isSeparate', 'MaxBlobs', 'DelRectOverlap', ...
        'rRate', 'gRate', 'bRate', 'keepNear', 'fixedTrackNum', 'fixedTrackDir', ...
        'contMin', 'contMax', 'sharpRadius', 'sharpAmount'};
end